# Generated by Django 3.2 on 2026-04-06 19:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cats', '0002_auto_20260405_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='image',
            field=models.ImageField(blank=True, upload_to='cats/'),
        ),
        migrations.AlterUniqueTogether(
            name='cat',
            unique_together={('name', 'owner')},
        ),
    ]
